name: Bug Report
description: File a bug report and help us to improve HestiaCP
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Please do not include any private or senstive information such as email adress, password or ip adresses. 
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to taken to repoduce the error?
      description: |
        What steps did you take when the issue occured?
        1. Ex. Click on the Web tab.
        2. Ex. Click on Add Web Domain.
        3. Ex. Attempted to add a domain and received an Internal Server Error.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version HestiaCP
      placeholder: 1.x.x
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: Ubuntu 20.04 or Debian 11
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
