name: Support / Question
description: Have a question regarding HestiaCP
title: "[Support] Don't use this form"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **Please do NOT use our GitHub Project for support requests, you can find community support and help here:**
        **Documentation:** [docs.hestiacp.com](https://docs.hestiacp.com/)
        **Forums:** [forum.hestiacp.com](https://forum.hestiacp.com/)
        **Discord:** [Join the discussion](https://discord.gg/8b2HGNe8ne)
  - type: checkboxes
    id: support
    attributes:
      label: Dont' use this form use any option above!
      description: You may select more than one.
      options:
        - label: Please use the other options above
          required: true
