name: Support / Question
description: Request for help, support, or to ask a general question
title: "[Support] Do not use this form! "
labels: [invalid]
body:
  - type: markdown
    attributes:
      value: |
        **Do not submit requests for support on GitHub! We use this platform for development purposes only.**
        If you need help or want to ask a question, use one of these options:

        * [Documentation](https://docs.hestiacp.com/)
        * [Discussion Forums](https://forum.hestiacp.com/)
        * [Discord (chat)](https://discord.gg/8b2HGNe8ne) (#community-support)
  - type: checkboxes
    id: support
    attributes:
      options:
        - label: I acknowledge that any support request submitted with this form will be closed.
          required: true
